if (CMAKE_VERSION VERSION_GREATER_EQUAL "3.12")
    macro(add_glob cur_list)
        file(GLOB __tmp RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} CONFIGURE_DEPENDS ${ARGN})
        list(APPEND ${cur_list} ${__tmp})
    endmacro()
else ()
    macro(add_glob cur_list)
        file(GLOB __tmp RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ${ARGN})
        list(APPEND ${cur_list} ${__tmp})
    endmacro()
endif ()

macro(add_headers_and_sources prefix common_path)
    add_glob(${prefix}_headers ${CMAKE_CURRENT_SOURCE_DIR} ${common_path}/*.h)
    add_glob(${prefix}_sources ${common_path}/*.cpp ${common_path}/*.c ${common_path}/*.h)
endmacro()

macro(add_headers_only prefix common_path)
    add_glob(${prefix}_headers ${CMAKE_CURRENT_SOURCE_DIR} ${common_path}/*.h)
endmacro()

macro(add_object_library name common_path)
    add_headers_and_sources(${name} ${common_path})
    add_library(${name}  ${${name}_sources} ${${name}_headers})
endmacro()

macro (dbms_target_link_libraries)
    foreach (module ${all_modules})
        target_link_libraries (${module} ${ARGN})
    endforeach ()
endmacro ()

macro (dbms_target_include_directories)
    foreach (module ${all_modules})
        target_include_directories (${module} ${ARGN})
    endforeach ()
endmacro ()
