# This will define
# LIBMEMCACHED_FOUND
# LIBMEMCACHED_INCLUDE_DIR
# LIBMEMCACHED_LIBRARY

find_path(LIBMEMCACHED_INCLUDE_DIR NAMES libmemcached/memcached.h)

find_library(LIBMEMCACHED_LIBRARY NAMES libmemcached.so)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    LIBMEMCACHED DEFAULT_MSG
    LIBMEMCACHED_LIBRARY LIBMEMCACHED_INCLUDE_DIR
)

if (LIBMEMCACHED_FOUND)
    message(STATUS "Found LIBMEMCACHED: ${LIBMEMCACHED_LIBRARY}")
endif()

mark_as_advanced(LIBMEMCACHED_INCLUDE_DIR LIBMEMCACHED_LIBRARY)
