# This will define
# BYTEDISK_FOUND
# BYTEDISK_INCLUDE_DIR
# BYTEDISK_LIBRARY

find_path(BYTEDISK_INCLUDE_DIR NAMES libbytedisk.h)

find_library(BYTEDISK_LIBRARY NAMES bytedisk)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    BYTEDISK DEFAULT_MSG
    BYTEDISK_LIBRARY BYTEDISK_INCLUDE_DIR
)

if (BYTEDISK_FOUND)
    message(STATUS "Found BYTEDISK: ${BYTEDISK_LIBRARY}")
endif()

mark_as_advanced(BYTEDISK_INCLUDE_DIR BYTEDISK_LIBRARY)
