// Copyright (c) 2022-present, ByteDance Inc. All rights reserved.
#pragma once

#include <gflags/gflags.h>

namespace bcache2 {
namespace metaserver {

DECLARE_string(metaserver_cluster_name);
DECLARE_int32(metaserver_server_port);
DECLARE_string(metaserver_work_dir);
DECLARE_string(metaserver_log_dir);
DECLARE_int32(metaserver_log_level);
DECLARE_int32(metaserver_log_file_num);
DECLARE_int32(metaserver_log_file_size);

DECLARE_string(metaserver_announce_consul_name);
DECLARE_string(metaserver_announce_consul_name_leader);

DECLARE_uint64(metaserver_task_scheduler_interval_ms);
DECLARE_uint64(metaserver_task_scheduler_max_inflight);
DECLARE_uint64(metaserver_task_scheduler_base_postpone_time_ms);
DECLARE_uint64(metaserver_task_scheduler_max_postpone_time_ms);

DECLARE_bool(metaserver_placement_host_deduplicate);
DECLARE_uint64(metaserver_placement_low_load_candidate_count);
DECLARE_uint64(metaserver_convict_routine_interval_ms);
DECLARE_uint64(metaserver_balance_routine_interval_ms);
DECLARE_double(metaserver_phi_failure_threshold);
DECLARE_uint64(metaserver_phi_interpret_pause_time_us);
DECLARE_uint64(metaserver_convict_safe_mode_warning_ratio);
DECLARE_uint64(metaserver_convict_safe_mode_critical_ratio);
DECLARE_bool(metaserver_convict_server_enabled);
DECLARE_bool(metaserver_convict_force_for_orphan_partition);
DECLARE_bool(metaserver_convict_proxy_enabled);
DECLARE_bool(metaserver_balance_enabled);
DECLARE_uint64(metaserver_max_balance_partition_per_round);
DECLARE_uint64(metaserver_balance_partition_count_safe_gap);

DECLARE_bool(metaserver_crash_on_fsm_failure);

DECLARE_bool(metaserver_freeze_missing_partition_enabled);
DECLARE_int64(metaserver_frozen_table_cool_down_time_sec);
DECLARE_int64(metaserver_frozen_partition_cool_down_time_sec);
DECLARE_int64(metaserver_loading_partition_max_loading_time_sec);
DECLARE_bool(metaserver_forbid_auto_register_for_convict_server);
DECLARE_uint64(metaserver_proxy_calibrate_interval_ms);

DECLARE_uint64(metaserver_table_default_evicter_max_memory_mb);
DECLARE_bool(metaserver_meta_query_allow_read_stale);
DECLARE_uint64(metaserver_meta_query_max_concurrency);

DECLARE_uint64(metaserver_meta_check_routine_interval_sec);
DECLARE_uint64(metaserver_meta_check_max_freeze_partition_per_min);
DECLARE_uint64(metaserver_missing_partition_reboot_grace_sec);

DECLARE_uint64(metaserver_raft_max_applied_log_bytes);
DECLARE_bool(metaserver_raft_metrics_on);
DECLARE_string(metaserver_raft_metrics_prefix);
DECLARE_uint64(metaserver_raft_id);
DECLARE_string(metaserver_raft_peers);
DECLARE_uint64(metaserver_raft_shard);
DECLARE_uint64(metaserver_raft_read_timeout_ms);
DECLARE_uint64(metaserver_raft_write_timeout_ms);
DECLARE_uint64(metaserver_raft_heartbeat_cycle_ms);
DECLARE_uint64(metaserver_raft_election_cycle_ms);
DECLARE_uint64(metaserver_raft_segment_size);
DECLARE_uint64(metaserver_raft_max_sync_log_size);
DECLARE_uint64(metaserver_raft_max_apply_log_size);
DECLARE_uint64(metaserver_raft_max_inflight_apply_task);
DECLARE_uint64(metaserver_raft_max_log_buffer_size);
DECLARE_bool(metaserver_raft_enable_reorder_queue);
DECLARE_uint64(metaserver_raft_reorder_queue_size);
DECLARE_uint64(metaserver_raft_reorder_cache_us);
DECLARE_bool(metaserver_raft_wal_sync);
DECLARE_string(metaserver_raft_log_file);
DECLARE_uint64(metaserver_raft_log_level);
DECLARE_uint64(metaserver_raft_worker_num);
DECLARE_uint64(metaserver_raft_reader_num);
DECLARE_uint64(metaserver_raft_flusher_num);
DECLARE_uint64(metaserver_raft_applier_num);
DECLARE_uint64(metaserver_raft_executor_num);
DECLARE_uint64(metaserver_raft_snapshot_num);
DECLARE_uint64(metaserver_raft_max_msgs_each_poll);
DECLARE_uint64(metaserver_raft_group_queue_max_depth);
DECLARE_uint64(metaserver_raft_transport_timeout_ms);
DECLARE_uint64(metaserver_snapshot_trigger_interval_sec);
DECLARE_uint64(metaserver_snapshot_trigger_index_gap);

}  // namespace metaserver
}  // namespace bcache2
