syntax = "proto3";

package bcache2.common2;

enum Function {
    DEL_OBJECT = 0;
    EXPIRE = 1;
    TTL = 2;
    EXISTS = 3;
    PERSIST = 4;
    OBJECT_TYPE = 5;
}

message DelObjectRequest {
    string key = 1;
}

message DelObjectResponse {
}

message ExpireRequest {
    string key = 1;
    uint64 ttl_ms = 2;
}

message ExpireResponse {
}

message TtlRequest {
    string key = 1;
}

message TtlResponse {
    uint64 ttl_ms = 1;
}

message ExistsRequest {
    string key = 1;
}

message ExistsResponse {
}

message PersistRequest {
    string key = 1;
}

message PersistResponse {
}

message ObjectTypeRequest {
    string key = 1;
}

message ObjectTypeResponse {
    uint32 model_id = 1;
}
