#!/usr/bin/env python3
"""Skill record builders for MatrixArk local ingestion."""

from __future__ import annotations

try:
    from tools.matrixark_mcp_core import Json, clip_context_text, stable_hash
except ModuleNotFoundError:  # Direct script execution from tools/.
    from matrixark_mcp_core import Json, clip_context_text, stable_hash


def skill_section_record(
    *,
    import_task_hash: int,
    skill_hash: int,
    section_hash: int,
    node_hash: int,
    node_path: list[str],
    raw_uri_hash: int,
    source_locator: str,
    heading: str,
    text: str,
    token_estimate: int,
    metadata: Json,
    access_scope: Json,
    deployment_scope: str,
    scope: Json,
    updated_at_ms: int,
) -> Json:
    return {
        "record_type": "skill_section",
        "import_task_hash": import_task_hash,
        "skill_hash": skill_hash,
        "section_hash": section_hash,
        "node_hash": node_hash,
        "node_path": node_path,
        "resource_hash": skill_hash,
        "raw_uri_hash": raw_uri_hash,
        "source_locator": source_locator,
        "heading": heading,
        "text": text,
        "token_estimate": token_estimate,
        "metadata": metadata,
        "access_scope": access_scope,
        "deployment_scope": deployment_scope,
        "scope": scope,
        "updated_at_ms": updated_at_ms,
    }


def skill_manifest_record(
    *,
    skill_hash: int,
    import_task_hash: int,
    node_hash: int,
    node_path: list[str],
    raw_uri: str,
    requested_raw_uri: str,
    raw_storage_mode: str,
    raw_storage_policy: str,
    storage_resolution: Json,
    name: str,
    description: str,
    metadata: Json,
    access_scope: Json,
    deployment_scope: str,
    text: str,
    token_estimate: int,
    serving_metadata: Json,
    scope: Json,
    storage_options: Json,
    updated_at_ms: int,
) -> Json:
    return {
        "record_type": "skill_manifest",
        "skill_hash": skill_hash,
        "import_task_hash": import_task_hash,
        "node_hash": node_hash,
        "node_path": node_path,
        "raw_uri": raw_uri,
        "requested_raw_uri": requested_raw_uri,
        "raw_storage_mode": raw_storage_mode,
        "raw_storage_policy": raw_storage_policy,
        "upload_status": storage_resolution.get("upload_status", "not_required"),
        "cloud_bucket": storage_resolution.get("cloud_bucket", ""),
        "cloud_key": storage_resolution.get("cloud_key", ""),
        "name": name,
        "description": description,
        "owner_scope": metadata.get("owner_scope", "user"),
        "version": metadata.get("version", "1"),
        "status": metadata.get("status", "active"),
        "precedence": metadata.get("precedence", "normal"),
        "triggers": metadata.get("triggers", []),
        "allowed_tools": metadata.get("allowed_tools", []),
        "examples": metadata.get("examples", []),
        "permissions": metadata.get("permissions", []),
        "inputs": metadata.get("inputs", []),
        "outputs": metadata.get("outputs", []),
        "access_scope": access_scope,
        "deployment_scope": deployment_scope,
        "text_preview": clip_context_text(text),
        "token_estimate": token_estimate,
        "metadata": serving_metadata,
        "scope": scope,
        "storage_options": storage_options,
        "updated_at_ms": updated_at_ms,
    }


def skill_parse_debug_record(
    *,
    skill_hash: int,
    import_task_hash: int,
    node_hash: int,
    node_path: list[str],
    raw_uri: str,
    metadata_debug: Json,
    text: str,
    scope: Json,
    updated_at_ms: int,
) -> Json:
    return {
        "record_type": "context_debug_record",
        "debug_type": "skill_parse_detail",
        "ref_type": "skill",
        "ref_hash": skill_hash,
        "skill_hash": skill_hash,
        "import_task_hash": import_task_hash,
        "node_hash": node_hash,
        "node_path": node_path,
        "raw_uri": raw_uri,
        "metadata_debug": metadata_debug,
        "text_preview": clip_context_text(text),
        "scope": scope,
        "updated_at_ms": updated_at_ms,
    }


def skill_registry_record(
    *,
    skill_hash: int,
    import_task_hash: int,
    raw_uri: str,
    requested_raw_uri: str,
    raw_storage_mode: str,
    raw_storage_policy: str,
    storage_resolution: Json,
    name: str,
    description: str,
    metadata: Json,
    access_scope: Json,
    deployment_scope: str,
    node_hash: int,
    node_path: list[str],
    scope: Json,
    updated_at_ms: int,
) -> Json:
    return {
        "record_type": "skill_registry",
        "registry_hash": stable_hash(f"skill_registry:{skill_hash}:{deployment_scope}"),
        "skill_hash": skill_hash,
        "import_task_hash": import_task_hash,
        "raw_uri": raw_uri,
        "requested_raw_uri": requested_raw_uri,
        "raw_storage_mode": raw_storage_mode,
        "raw_storage_policy": raw_storage_policy,
        "upload_status": storage_resolution.get("upload_status", "not_required"),
        "cloud_bucket": storage_resolution.get("cloud_bucket", ""),
        "cloud_key": storage_resolution.get("cloud_key", ""),
        "name": name,
        "description": description,
        "owner_scope": metadata.get("owner_scope", "user"),
        "version": metadata.get("version", "1"),
        "status": metadata.get("status", "active"),
        "precedence": metadata.get("precedence", "normal"),
        "triggers": metadata.get("triggers", []),
        "allowed_tools": metadata.get("allowed_tools", []),
        "examples": metadata.get("examples", []),
        "permissions": metadata.get("permissions", []),
        "inputs": metadata.get("inputs", []),
        "outputs": metadata.get("outputs", []),
        "access_scope": access_scope,
        "deployment_scope": deployment_scope,
        "node_hash": node_hash,
        "node_path": node_path,
        "scope": scope,
        "updated_at_ms": updated_at_ms,
    }
