#!/usr/bin/env python3
"""Runtime config compatibility exports for matrixark_mcp_core."""

from __future__ import annotations

import importlib
from typing import Any

RUNTIME_CONFIG_EXPORTS = (
    "AUDIT_DEBUG_PAYLOAD",
    "BACKEND_READINESS_BACKOFF_MS",
    "BACKEND_READINESS_CONNECT_TIMEOUT_MS",
    "BACKEND_READINESS_TIMEOUT_MS",
    "CONTEXT_PACK_DEBUG_REFS",
    "CONTEXT_TELEMETRY_WRITE_MODE",
    "DEFAULT_BUDGET_FILL_POLICY",
    "DEFAULT_BUSINESS_TYPE_WEIGHTS",
    "DEFAULT_BUSINESS_WEIGHT",
    "DEFAULT_CROSS_SESSION_BROAD_BUDGET_RATIO",
    "DEFAULT_CROSS_SESSION_BUDGET_RATIO",
    "DEFAULT_CROSS_SESSION_CURRENT_STATE_BUDGET_RATIO",
    "DEFAULT_CROSS_SESSION_MAX_BUDGET_RATIO",
    "DEFAULT_CROSS_SESSION_MAX_BUDGET_TOKENS",
    "DEFAULT_CROSS_SESSION_MAX_CANDIDATES",
    "DEFAULT_CROSS_SESSION_MAX_SESSIONS",
    "DEFAULT_CROSS_SESSION_MIN_BUDGET_TOKENS",
    "DEFAULT_CROSS_SESSION_MIN_ENTITY_BRIDGE_REFS",
    "DEFAULT_CROSS_SESSION_MIN_SCORE",
    "DEFAULT_CROSS_SESSION_MULTI_HOP_BUDGET_RATIO",
    "DEFAULT_CROSS_SESSION_PARALLELISM",
    "DEFAULT_CROSS_SESSION_PREFERRED_REF_TYPES",
    "DEFAULT_CROSS_SESSION_RAW_EVIDENCE_MIN_SCORE",
    "DEFAULT_ENTITY_MERGE_OPERATOR",
    "DEFAULT_MAX_CANDIDATES_PER_NODE",
    "DEFAULT_MAX_CHILDREN_SCORED_PER_PARENT",
    "DEFAULT_MAX_CONTEXT_TOKENS",
    "DEFAULT_MAX_GLOBAL_CANDIDATES",
    "DEFAULT_MAX_SELECTED_REFS",
    "DEFAULT_RETRIEVAL_MIN_SCORE",
    "DEFAULT_SHARED_CONTEXT_MIN_SCORE",
    "DEFAULT_SHARED_RESOURCE_BUDGET_RATIO",
    "DEFAULT_SHARED_RESOURCE_MAX_BUDGET_RATIO",
    "DEFAULT_SHARED_RESOURCE_MAX_BUDGET_TOKENS",
    "DEFAULT_SHARED_SKILL_BUDGET_RATIO",
    "DEFAULT_SHARED_SKILL_MAX_BUDGET_RATIO",
    "DEFAULT_SHARED_SKILL_MAX_BUDGET_TOKENS",
    "DEFAULT_TIME_DECAY_HALFLIFE_MS",
    "DEFAULT_TIME_DECAY_TOLERANCE_MS",
    "DEFAULT_TIME_WEIGHT",
    "DEFAULT_TOP_K_PER_LAYER",
    "DIRECT_AUDIT_BUFFER_MAX_RECORDS",
    "DIRECT_AUDIT_FLUSH_INTERVAL_MS",
    "DIRECT_AUDIT_MODE",
    "DIRECT_RECORD_BUNDLE_MAX_BYTES",
    "DIRECT_RECORD_HOT_CACHE_MAX_RECORDS",
    "DIRECT_RECORD_LOG_SHARD_SIZE",
    "DIRECT_WRITE_BACKOFF_MS",
    "DIRECT_WRITE_RETRIES",
    "DIRECT_WRITE_THROTTLE_MS",
    "ENABLE_CONTEXT_DEBUG_RECORDS",
    "ENABLE_CONTEXT_REPLAY",
    "ENABLE_LLM_MERGE_OPERATOR",
    "ENABLE_SUMMARY_REFRESH_AUDIT",
    "HARD_MAX_CHILDREN_SCORED_PER_PARENT",
    "MATRIXARK_ALLOW_LOCAL_BACKEND",
    "MATRIXARK_ALLOW_PYTHON_HOT_CACHE",
    "MATRIXARK_MCP_PROFILE",
    "MATRIXARK_REQUIRE_BACKEND_READY",
    "MATRIXARK_REQUIRE_NATIVE_CANDIDATE_PREFILTER",
    "MATRIXARK_REQUIRE_NATIVE_CONTEXT_PACK",
    "MAX_PRIOR_CHARS",
    "MAX_PRIOR_MESSAGES",
    "matrixark_production_profile_enabled",
    "native_candidate_prefilter_required",
    "python_hot_cache_allowed",
    "RESOURCE_ASYNC_DEFAULT_BYTES",
    "RESOURCE_ASYNC_DEFAULT_PATH_COUNT",
    "RESOURCE_ASYNC_DEFAULT_TEXT_CHARS",
    "SUMMARY_REFRESH_INTERVAL_MS",
    "SUMMARY_REFRESH_LIMIT",
    "TIME_COMPRESSION_MAX_RAW_EVENTS_PER_NODE",
    "TIME_COMPRESSION_MAX_WINDOWS_PER_REFRESH",
    "TIME_COMPRESSION_MIN_EVENTS",
    "TIME_COMPRESSION_MIN_EVENT_AGE_MS",
    "TIME_COMPRESSION_RAW_EVENT_TTL_AFTER_COMPRESSION_MS",
    "TIME_COMPRESSION_REINFORCEMENT_PROTECT_MS",
    "TIME_COMPRESSION_WINDOW_EVENTS",
)



def runtime_config_exports() -> dict[str, Any]:
    try:
        runtime_config = importlib.import_module("tools.matrixark_mcp_runtime_config")
    except ModuleNotFoundError:  # Direct script execution from tools/.
        runtime_config = importlib.import_module("matrixark_mcp_runtime_config")
    return {name: getattr(runtime_config, name) for name in RUNTIME_CONFIG_EXPORTS}
