#!/usr/bin/env python3
"""Response payload builders for MatrixArk local ingestion."""

from __future__ import annotations

from typing import Any

try:
    from tools.matrixark_mcp_core import (
        MAX_INDEX_TERMS_PER_RESOURCE_CHUNK,
        MAX_INDEX_TERMS_PER_RESOURCE_FACT,
        Json,
        embedding_execution_mode_name,
        embedding_fallback_used,
        embedding_model_name,
        session_buffer_key,
    )
except ModuleNotFoundError:  # Direct script execution from tools/.
    from matrixark_mcp_core import (
        MAX_INDEX_TERMS_PER_RESOURCE_CHUNK,
        MAX_INDEX_TERMS_PER_RESOURCE_FACT,
        Json,
        embedding_execution_mode_name,
        embedding_fallback_used,
        embedding_model_name,
        session_buffer_key,
    )


def build_resource_import_queued_response(
    *,
    event_id_hash: int,
    node_hash: int,
    resource_import_task_hash: int,
    requested_raw_uri: str,
    resource_type: str,
    storage_resolution: Json,
    raw_storage_policy: str,
    queue_status: Any,
    async_default_reason: str,
    node_materialization: Json,
) -> Json:
    return {
        "status": "queued",
        "event_id_hash": event_id_hash,
        "node_hash": node_hash,
        "resource_import_task": {
            "task_hash": resource_import_task_hash,
            "status": "queued",
            "wait": False,
            "background_started": True,
            "raw_uri": requested_raw_uri,
            "requested_raw_uri": requested_raw_uri,
            "resource_type": resource_type,
            "raw_storage_mode": storage_resolution["storage_mode"],
            "raw_storage_policy": raw_storage_policy,
            "raw_bytes_stored": False,
            "worker_pool": queue_status,
            "progress": {"stage": "queued", "percent": 0},
            "async_default_reason": async_default_reason,
        },
        "node_materialization": node_materialization,
    }


def build_ingest_response(
    *,
    envelope: Json,
    hook: Json | None,
    event_id_hash: int,
    node_hash: int,
    extraction: Json,
    summary_refresh: Json,
    resource_dirty_hashes: list[int],
    resource_import_task_hash: int,
    resource_import_task_status: str,
    resource_import_wait: bool,
    resource_import_metrics: Json,
    raw_uri: str,
    requested_raw_uri: str,
    storage_resolution: Json,
    raw_storage_policy: str,
    node_materialization: Json,
    resource_chunk_hashes: list[int],
    original_chunk_count: int,
    deduped_chunk_count: int,
    deduped_source_refs: list[str],
    resource_version_value: str,
    resource_content_hash: str,
    parse_warnings: list[str],
    superseded_chunk_count: int,
    superseded_chunk_hashes: list[int],
    resource_fact_event_hashes: list[int],
    resource_fact_entity_hashes: list[int],
    index_candidate_count: int,
    index_write_count: int,
    index_dropped_by_cap_count: int,
    skill_hash: int | None,
    session_buffer_enabled: bool,
    pending_event_count: int,
    pending_message_count: int,
    session_buffer_threshold: int,
    threshold_ready: bool,
    idle_schedule: Json | None,
    auto_batch_extract: bool,
    session_boundary_commit: bool,
    idle_commit_result: Json,
    auto_batch_result: Json | None,
    backend_readiness: Json | None,
) -> Json:
    is_resource_like = envelope["kind"] in {"resource", "skill"}
    return {
        "status": "accepted",
        "event_id_hash": event_id_hash,
        "node_hash": node_hash,
        "storage_options": envelope.get("storage_options", {}),
        "storage_route": envelope.get("storage_route", {}),
        "hook_captured": hook is not None,
        "embedding_model": embedding_model_name(),
        "embedding_execution_mode": embedding_execution_mode_name(),
        "embedding_fallback_used": embedding_fallback_used(),
        "extraction_mode": extraction["mode"],
        "classification": extraction.get("classification", "UNCLASSIFIED"),
        "prior_context": extraction.get("prior_context", ""),
        "prior_refs": extraction.get("prior_refs", []),
        "prior_message_count": extraction.get("prior_message_count", 0),
        "prior_summary_count": extraction.get("prior_summary_count", 0),
        "quality_warning": extraction.get("quality_warning", ""),
        "summary_refresh": summary_refresh,
        "resource_summary_refresh": {
            "status": "dirty_marked" if resource_dirty_hashes else "not_applicable",
            "dirty_hashes": resource_dirty_hashes,
            "refresh_result": None,
            "async_required": bool(resource_dirty_hashes),
        },
        "resource_import_task": {
            "task_hash": resource_import_task_hash,
            "status": resource_import_task_status,
            "wait": resource_import_wait,
            "metrics": resource_import_metrics,
            "raw_uri": raw_uri if resource_import_task_hash else "",
            "requested_raw_uri": requested_raw_uri if resource_import_task_hash else "",
            "raw_storage_mode": storage_resolution.get("storage_mode", "") if resource_import_task_hash else "",
            "raw_storage_policy": raw_storage_policy if resource_import_task_hash else "",
            "raw_bytes_stored": False if resource_import_task_hash else None,
            "upload_status": storage_resolution.get("upload_status", "") if resource_import_task_hash else "",
            "cloud_bucket": storage_resolution.get("cloud_bucket", "") if resource_import_task_hash else "",
            "cloud_key": storage_resolution.get("cloud_key", "") if resource_import_task_hash else "",
            "progress": {"stage": resource_import_task_status, "percent": 100 if resource_import_task_status == "completed" else 0},
        },
        "node_materialization": node_materialization,
        "resource_chunks": resource_chunk_hashes,
        "resource_chunk_count": len(resource_chunk_hashes),
        "resource_original_chunk_count": original_chunk_count if is_resource_like else 0,
        "resource_deduped_chunk_count": deduped_chunk_count if is_resource_like else 0,
        "resource_deduped_source_refs": deduped_source_refs[:20] if is_resource_like else [],
        "resource_version": resource_version_value if is_resource_like else "",
        "resource_content_hash": resource_content_hash if is_resource_like else "",
        "resource_parse_warnings": parse_warnings if is_resource_like else [],
        "resource_parse_warning_count": len(parse_warnings) if is_resource_like else 0,
        "resource_raw_uri": raw_uri if is_resource_like else "",
        "resource_requested_raw_uri": requested_raw_uri if is_resource_like else "",
        "resource_raw_storage_mode": storage_resolution.get("storage_mode", "") if is_resource_like else "",
        "resource_raw_storage_policy": raw_storage_policy if is_resource_like else "",
        "resource_raw_bytes_stored": False if is_resource_like else None,
        "backend_readiness": backend_readiness or {},
        "resource_superseded_chunk_count": superseded_chunk_count if is_resource_like else 0,
        "resource_superseded_chunk_hashes": superseded_chunk_hashes if is_resource_like else [],
        "resource_fact_events": resource_fact_event_hashes,
        "resource_fact_event_count": len(resource_fact_event_hashes),
        "resource_fact_entities": resource_fact_entity_hashes,
        "resource_fact_entity_count": len(resource_fact_entity_hashes),
        "resource_index_candidate_count": index_candidate_count if is_resource_like else 0,
        "resource_index_write_count": index_write_count if is_resource_like else 0,
        "resource_index_dropped_by_cap_count": index_dropped_by_cap_count if is_resource_like else 0,
        "resource_index_cap_per_chunk": MAX_INDEX_TERMS_PER_RESOURCE_CHUNK,
        "resource_index_cap_per_fact": MAX_INDEX_TERMS_PER_RESOURCE_FACT,
        "skill_hash": skill_hash,
        "session_buffer": {
            "enabled": session_buffer_enabled,
            "buffer_key": list(session_buffer_key(envelope)),
            "pending_event_count": pending_event_count,
            "pending_message_count": pending_message_count,
            "threshold_messages": session_buffer_threshold,
            "threshold_ready": threshold_ready,
            **(idle_schedule or {}),
            "auto_batch_extract": auto_batch_extract,
            "boundary_commit_requested": session_boundary_commit,
        },
        "idle_commit_result": idle_commit_result,
        "auto_batch_extract_result": auto_batch_result,
    }
