#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

BUILD_TYPE="${BUILD_TYPE:-Release}"
RESULT_DIR="${RESULT_DIR:-/tmp/temporalstore-raft-production-gate-$(date +%Y%m%d_%H%M%S)}"
ITERATIONS="${ITERATIONS:-5}"
FAILOVER_ITERATIONS="${FAILOVER_ITERATIONS:-5}"
BASE_MS_PORT="${BASE_MS_PORT:-21000}"
BASE_SERVER_PORT="${BASE_SERVER_PORT:-11000}"
PORT_STRIDE="${PORT_STRIDE:-700}"
THREAD_LIST="${THREAD_LIST:-2 4}"
OPS="${OPS:-3000}"
MEMBERSHIP_OPS="${MEMBERSHIP_OPS:-600}"
BENCH_TIMEOUT_S="${BENCH_TIMEOUT_S:-300}"
MIXED_PROBE_OPS="${MIXED_PROBE_OPS:-600}"
MIXED_PROBE_THREADS="${MIXED_PROBE_THREADS:-4}"
RAFT_SNAPSHOT_OPS="${RAFT_SNAPSHOT_OPS:-300}"
RAFT_SNAPSHOT_THREADS="${RAFT_SNAPSHOT_THREADS:-2}"

RAFT_MAX_METASERVER_FAILOVER_MS="${RAFT_MAX_METASERVER_FAILOVER_MS:-10000}"
RAFT_MAX_DATA_FAILOVER_WRITE_READ_MS="${RAFT_MAX_DATA_FAILOVER_WRITE_READ_MS:-10000}"
RAFT_MAX_SECONDARY_VISIBILITY_P99_US="${RAFT_MAX_SECONDARY_VISIBILITY_P99_US:-50000}"
RAFT_MAX_POST_FAILOVER_APPLY_LAG="${RAFT_MAX_POST_FAILOVER_APPLY_LAG:-128}"
RAFT_MAX_2NODE_SCALE_P99_US="${RAFT_MAX_2NODE_SCALE_P99_US:-150000}"

echo "result_dir=${RESULT_DIR}"
echo "iterations=${ITERATIONS}"
echo "failover_iterations=${FAILOVER_ITERATIONS}"
echo "thread_list=${THREAD_LIST}"
echo "ops=${OPS}"
echo "membership_ops=${MEMBERSHIP_OPS}"
echo "max_metaserver_failover_ms=${RAFT_MAX_METASERVER_FAILOVER_MS}"
echo "max_data_failover_write_read_ms=${RAFT_MAX_DATA_FAILOVER_WRITE_READ_MS}"
echo "max_secondary_visibility_p99_us=${RAFT_MAX_SECONDARY_VISIBILITY_P99_US}"
echo "max_post_failover_apply_lag=${RAFT_MAX_POST_FAILOVER_APPLY_LAG}"
echo "max_2node_scale_p99_us=${RAFT_MAX_2NODE_SCALE_P99_US}"

env \
  BUILD_TYPE="${BUILD_TYPE}" \
  RESULT_DIR="${RESULT_DIR}" \
  ITERATIONS="${ITERATIONS}" \
  FAILOVER_ITERATIONS="${FAILOVER_ITERATIONS}" \
  BASE_MS_PORT="${BASE_MS_PORT}" \
  BASE_SERVER_PORT="${BASE_SERVER_PORT}" \
  PORT_STRIDE="${PORT_STRIDE}" \
  THREAD_LIST="${THREAD_LIST}" \
  OPS="${OPS}" \
  MEMBERSHIP_OPS="${MEMBERSHIP_OPS}" \
  BENCH_TIMEOUT_S="${BENCH_TIMEOUT_S}" \
  MIXED_PROBE_OPS="${MIXED_PROBE_OPS}" \
  MIXED_PROBE_THREADS="${MIXED_PROBE_THREADS}" \
  RAFT_SNAPSHOT_OPS="${RAFT_SNAPSHOT_OPS}" \
  RAFT_SNAPSHOT_THREADS="${RAFT_SNAPSHOT_THREADS}" \
  RUN_META_MEMBERSHIP="${RUN_META_MEMBERSHIP:-1}" \
  RUN_META_FAILOVER="${RUN_META_FAILOVER:-1}" \
  RUN_DATA_MEMBERSHIP="${RUN_DATA_MEMBERSHIP:-1}" \
  RUN_2NODE_SCALE="${RUN_2NODE_SCALE:-1}" \
  RUN_MIXED_RW="${RUN_MIXED_RW:-1}" \
  RUN_DATA_SNAPSHOT="${RUN_DATA_SNAPSHOT:-1}" \
  RUN_FAILOVER="${RUN_FAILOVER:-1}" \
  RAFT_PRODUCTION_ASSERTIONS=1 \
  RAFT_MAX_METASERVER_FAILOVER_MS="${RAFT_MAX_METASERVER_FAILOVER_MS}" \
  RAFT_MAX_DATA_FAILOVER_WRITE_READ_MS="${RAFT_MAX_DATA_FAILOVER_WRITE_READ_MS}" \
  RAFT_MAX_SECONDARY_VISIBILITY_P99_US="${RAFT_MAX_SECONDARY_VISIBILITY_P99_US}" \
  RAFT_MAX_POST_FAILOVER_APPLY_LAG="${RAFT_MAX_POST_FAILOVER_APPLY_LAG}" \
  RAFT_MAX_2NODE_SCALE_P99_US="${RAFT_MAX_2NODE_SCALE_P99_US}" \
  bash "${ROOT}/tools/run_raft_stress_suite_ubuntu22.sh"
