#!/usr/bin/env bash

# Shared runtime defaults for local smoke, AWS scale tests, and cache tests.
# Override any value by exporting the matching TEMPORALSTORE_* variable.
#
# MatrixArk/C++/Rust parity knobs use the TS_* names below.  C++ still maps the
# storage-facing subset into the existing gflags, while Rust reads the same
# names through StorageTuningConfig.

TS_CONTEXT_PAGE_TARGET_BYTES="${TS_CONTEXT_PAGE_TARGET_BYTES:-65536}"
TS_BLOCK_SEGMENT_TARGET_BYTES="${TS_BLOCK_SEGMENT_TARGET_BYTES:-1073741824}"
TS_STORAGE_ZONE_SIZE="${TS_STORAGE_ZONE_SIZE:-10485760}"
TS_STREAM_MAX_BLOB_SIZE="${TS_STREAM_MAX_BLOB_SIZE:-10485760}"
TS_COMPACTION_WATERMARK_BYTES="${TS_COMPACTION_WATERMARK_BYTES:-268435456}"
TS_COLD_SCAN_NO_CACHE_FILL="${TS_COLD_SCAN_NO_CACHE_FILL:-true}"

TEMPORALSTORE_STORAGE_EXTENT_SIZE="${TEMPORALSTORE_STORAGE_EXTENT_SIZE:-${TEMPORALSTORE_STORAGE_ZONE_SIZE:-${TS_STORAGE_ZONE_SIZE}}}"
TEMPORALSTORE_STORAGE_ZONE_SIZE="${TEMPORALSTORE_STORAGE_ZONE_SIZE:-${TEMPORALSTORE_STORAGE_EXTENT_SIZE}}"
TEMPORALSTORE_STREAM_MAX_BLOB_SIZE="${TEMPORALSTORE_STREAM_MAX_BLOB_SIZE:-${TS_STREAM_MAX_BLOB_SIZE}}"
TEMPORALSTORE_STORAGE_ASYNC="${TEMPORALSTORE_STORAGE_ASYNC:-false}"
TEMPORALSTORE_STORAGE_OPLOG_DELAY_DUMP_LENGTH="${TEMPORALSTORE_STORAGE_OPLOG_DELAY_DUMP_LENGTH:-0}"

# Keep TS_* aliases synchronized after legacy TEMPORALSTORE_* overrides resolve.
TS_STORAGE_ZONE_SIZE="${TEMPORALSTORE_STORAGE_ZONE_SIZE}"
TS_STREAM_MAX_BLOB_SIZE="${TEMPORALSTORE_STREAM_MAX_BLOB_SIZE}"

TEMPORALSTORE_REPLICATOR_OUT_OF_SYNC_S="${TEMPORALSTORE_REPLICATOR_OUT_OF_SYNC_S:-${REPLICATOR_OUT_OF_SYNC_S:-10}}"
TEMPORALSTORE_REPLICATOR_LOOP_INTERVAL_US="${TEMPORALSTORE_REPLICATOR_LOOP_INTERVAL_US:-1000}"
TEMPORALSTORE_REPLICATOR_MAX_OPLOG_PER_LOOP="${TEMPORALSTORE_REPLICATOR_MAX_OPLOG_PER_LOOP:-20000}"
TEMPORALSTORE_REPLICATOR_MAX_INDEXLOG_PER_LOOP="${TEMPORALSTORE_REPLICATOR_MAX_INDEXLOG_PER_LOOP:-20000}"
TEMPORALSTORE_REPLICATOR_UPDATE_REMOTE_INTERVAL_MS="${TEMPORALSTORE_REPLICATOR_UPDATE_REMOTE_INTERVAL_MS:-20}"

TEMPORALSTORE_ENABLE_BLOCKCACHE="${TEMPORALSTORE_ENABLE_BLOCKCACHE:-true}"
TEMPORALSTORE_BLOCKCACHE_SSD_ENGINE_TYPE="${TEMPORALSTORE_BLOCKCACHE_SSD_ENGINE_TYPE:-0}"
TEMPORALSTORE_BLOCKCACHE_DRAM_CAPACITY="${TEMPORALSTORE_BLOCKCACHE_DRAM_CAPACITY:-8388608}"
TEMPORALSTORE_BLOCKCACHE_SSD_CAPACITY="${TEMPORALSTORE_BLOCKCACHE_SSD_CAPACITY:-67108864}"
TEMPORALSTORE_BLOCKCACHE_SSD_PATH="${TEMPORALSTORE_BLOCKCACHE_SSD_PATH:-/tmp/temporalstore-server-ssd-cache}"
TEMPORALSTORE_BLOCKCACHE_SSD_INSTANCE_ONLY="${TEMPORALSTORE_BLOCKCACHE_SSD_INSTANCE_ONLY:-true}"
TEMPORALSTORE_BLOCKCACHE_CLEAR_SSD_FOLDER="${TEMPORALSTORE_BLOCKCACHE_CLEAR_SSD_FOLDER:-false}"

temporalstore_storage_flags() {
  printf '%s\n' \
    "--storage_zone_size=${TEMPORALSTORE_STORAGE_ZONE_SIZE}" \
    "--stream_max_blob_size=${TEMPORALSTORE_STREAM_MAX_BLOB_SIZE}" \
    "--storage_async=${TEMPORALSTORE_STORAGE_ASYNC}" \
    "--storage_oplog_delay_dump_length=${TEMPORALSTORE_STORAGE_OPLOG_DELAY_DUMP_LENGTH}"
}

temporalstore_replicator_flags() {
  printf '%s\n' \
    "--replicator_out_of_sync_s=${TEMPORALSTORE_REPLICATOR_OUT_OF_SYNC_S}" \
    "--replicator_loop_interval_us=${TEMPORALSTORE_REPLICATOR_LOOP_INTERVAL_US}" \
    "--replicator_max_oplog_per_loop=${TEMPORALSTORE_REPLICATOR_MAX_OPLOG_PER_LOOP}" \
    "--replicator_max_indexlog_per_loop=${TEMPORALSTORE_REPLICATOR_MAX_INDEXLOG_PER_LOOP}" \
    "--replicator_update_remote_interval_ms=${TEMPORALSTORE_REPLICATOR_UPDATE_REMOTE_INTERVAL_MS}"
}

temporalstore_replicator_loop_flags() {
  printf '%s\n' \
    "--replicator_loop_interval_us=${TEMPORALSTORE_REPLICATOR_LOOP_INTERVAL_US}" \
    "--replicator_max_oplog_per_loop=${TEMPORALSTORE_REPLICATOR_MAX_OPLOG_PER_LOOP}" \
    "--replicator_max_indexlog_per_loop=${TEMPORALSTORE_REPLICATOR_MAX_INDEXLOG_PER_LOOP}" \
    "--replicator_update_remote_interval_ms=${TEMPORALSTORE_REPLICATOR_UPDATE_REMOTE_INTERVAL_MS}"
}

temporalstore_blockcache_flags() {
  printf '%s\n' \
    "--enable_blockcache=${TEMPORALSTORE_ENABLE_BLOCKCACHE}" \
    "--ssd_engine_type=${TEMPORALSTORE_BLOCKCACHE_SSD_ENGINE_TYPE}" \
    "--blockcache_dram_capacity=${TEMPORALSTORE_BLOCKCACHE_DRAM_CAPACITY}" \
    "--blockcache_ssd_capacity=${TEMPORALSTORE_BLOCKCACHE_SSD_CAPACITY}" \
    "--blockcache_ssd_path=${TEMPORALSTORE_BLOCKCACHE_SSD_PATH}" \
    "--blockcache_ssd_instance_only=${TEMPORALSTORE_BLOCKCACHE_SSD_INSTANCE_ONLY}" \
    "--blockcache_clear_ssd_folder=${TEMPORALSTORE_BLOCKCACHE_CLEAR_SSD_FOLDER}"
}
